site_name: My Knowledge Base
theme:
  name: material 
  palette:
    scheme: slate

plugins:
  - search

nav:
  - Home: index.md
  - Bash Scripting: bashguide.md
  - Cherrytree: cherry.md
  - cUrl: curl.md
  - Linux Commands: linux-commands.md
  - Linux Users and Privileges: linuxuserpriv.md
  - Mapping Hostnames to IPs: hostnamemapping.md
  - Networking: networking.md
  - Python Networking: pynet.md
  
  - H4X:
    - Bruteforce Attacks: bruteforce.md
    - Buffer Overflow x86: B0x86.md
    - Hacking Methodology: hmet.md
    - Information Gathering Tools: igtools.md
    - MSFconsole: msfc.md
    - Researching Vulnerabilities: revul.md
    - Scanning and Enumeration: scanenum.md
    - Shell Exploitation: shell.md
    - SMB (Server Message Block): smb.md
    - SSH (Secure Shell): ssh.md
    - Wordpress exploitation: wpexplo.md
    - Burpsuite - Stuffing & Spraying: burpspray.md
    - Proxychains Tor: torproxy.md
    
  - HTB:
    - Three - S3 Reverse Shell: threeawsshell.md
  - MkDocs:  
    - Create post: create.md
    - Create Virtual Enviroment: venv.md
    - Formatting Guide: mkdocs-formatting-guide.md
    - Github create & update: github.md
