name: Build and Deploy MkDocs Site

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Allows the workflow to push changes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}  # Optional: prevents overlapping deployments
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MkDocs and Theme
        run: |
          pip install --upgrade mkdocs mkdocs-material

      - name: Build the Site
        run: mkdocs build  # This will generate your site into the "site" folder

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # This is the branch the action will deploy to (default is gh-pages)
          folder: site      # The folder containing your built site
